name: Deploy_to_AWS
env:
  APP_NAME: "My_Application"
  BUCKET_NAME: "elad-sadna-test"
  PACKAGE_NAME: "my_app_version:${{ github.sha }}.zip"
  AWS_REGION_NAME: "ca-central-1"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: aws --version
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{  secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create Package
        run: zip -r ${{ env.PACKAGE_NAME }} ./ -x *.git*

      - name: Send Package
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.BUCKET_NAME }}/
