name: Deploy_to_AWS
env:
  APP_NAME: "My_Application"
  BUCKET_NAME: "elad-sadna-test"
  PACKAGE_NAME: "my_app_version: ${{ github-sha }}.zip"
  AWS_REGION_NAME: "ca-central-1"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: aws --version
