name: Deploy to EC2
env:
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        echo "${{ secrets.MY_PRIVATE_KEY }}" > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}

    - name: SSH into EC2 instance and execute commands
      run: |
        ssh -i ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }} ubuntu@15.222.12.15 'sudo apt intall apache2'
