name: Deploy_to_AWS
env:
  Server_Name: "elad_sadna_test"
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
  HOST_NAME: "3.96.57.227"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: mkdir .ssh and copy private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PRIVATE_KEY }}" > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
          chmod 600 ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
          ls -la ~/.ssh
          pwd
          sudo apt update
          sudo apt install openssh-client
          sudo apt install awscli
          
      - name: Install Apache2
        run: sudo apt install apache2

      - name: Deploy index.html
        uses: appleboy/scp-action@master
        with:
         source: "./index.html"
         target: "/var/www/html/"
         host: ${{ env.HOST_NAME }}
         username: ubuntu
         key: ${{ secrets.MY_PRIVATE_KEY }}
