name: Deploy to EC2

env:
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
  EC2_PUBLIC_IP: "15.222.12.15"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure SSH
      run: |
        echo "${{ secrets.MY_PRIVATE_KEY }}" > ~/.ssh/${NAME_OF_PRIVATE_KEY}
        chmod 600 ~/.ssh/${NAME_OF_PRIVATE_KEY}
        ls -la
        pwd

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/${NAME_OF_PRIVATE_KEY} ubuntu@${EC2_PUBLIC_IP} 'sudo apt install apache2'
