name: Deploy_to_AWS
env:
  Server_Name: "elad_sadna_test"
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo private key
        run: |
          echo "${{ secrets.MY_PRIVATE_KEY }} > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}" && ls -la && pwd
          ssh -i ~/.ssh/elad_ca-central-1.pem ubuntu@3.96.57.227
