name: Deploy_to_AWS
env:
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: mkdir .ssh and copy private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PRIVATE_KEY }}" > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
          chmod 600 ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
          ls -la ~/.ssh
          pwd
        
      - name: Install SSH client
        run: sudo apt install openssh-client

      - name: Install Apache2
        run: sudo apt install apache2 && sudo apt update
