name: Deploy_to_AWS
env:
  Server_Name: "elad_sadna_test"
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo private key
        run: echo "${{ secrets.MY_PRIVATE_KEY }} > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}" || pwd

      - name: mkdir .ssh
        run: mkdir -p ~/.ssh

      - name: Copy index.html
        run: scp -i "${{ env.NAME_OF_PRIVATE_KEY }}" Git_deploy_Sadna_2aws/index.html ${{ secrets.USER_NAME }}:/var/www/html/
        
      
       
        # run: ssh -i ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }} ${{ secrets.USER_NAME }}

      - name: Install SSH client
        run: sudo apt install openssh-client

      - name: Install Apache2
        run: sudo apt install apache2 && sudo apt update


